"""Publish knowledge documents as Claude Code skills (docs/11 §11.8).

The same substrate serves the runtime generation agents and the coding agents
working in this repo. A pattern like "how we structure a service module" or
"the prompt-assembly invariants" is useful to a human reading docs, to the
generator, and to whatever is writing code here — and writing it once means the
three cannot drift apart.

Generated, never hand-edited. ``.claude/skills/`` is derived from
``knowledge/``; editing it directly would create exactly the drift this is
meant to prevent, so every generated file says so at the top.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

from braingames_core.costs import atomic_write

from .loader import KnowledgeBase
from .models import Doc, Stage
from .router import sort_key

GENERATED_MARKER = "<!-- GENERATED by `bg kb sync-skills`. Edit knowledge/ instead. -->"


@dataclass(frozen=True)
class SkillSpec:
    """One published skill: a name, a trigger description, and its documents."""

    name: str
    description: str
    stages: tuple[Stage, ...]


#: Which stages become which skill. Splitting by stage rather than shipping one
#: giant skill keeps each description specific enough to trigger accurately —
#: a skill that claims to cover everything gets loaded for everything.
SKILLS: tuple[SkillSpec, ...] = (
    SkillSpec(
        name="braingames-backend",
        description=(
            "Conventions for Braingames backend code: service module structure, the "
            "knowledge base, prompt assembly and its caching invariants, metered model "
            "calls, and cost accounting. Use when writing or reviewing Python in "
            "packages/, api/, or worker/."
        ),
        stages=(Stage.CODEGEN_BACKEND,),
    ),
    SkillSpec(
        name="braingames-frontend",
        description=(
            "Conventions for Braingames frontend code: the game module contract, grid "
            "rendering and input handling, offline-first solving, and theme integration. "
            "Use when writing or reviewing TypeScript in web/."
        ),
        stages=(Stage.CODEGEN_FRONTEND,),
    ),
    SkillSpec(
        name="braingames-theming",
        description=(
            "The theme engine contract and scene patterns: token schema, the CSS "
            "allowlist, the sandboxed ThemeScene interface, and frame-budget-safe "
            "animation. Use when writing, generating, or reviewing theme code."
        ),
        stages=(Stage.THEME_SCENE_GENERATION,),
    ),
    SkillSpec(
        name="braingames-puzzles",
        description=(
            "Crossword construction and cluing standards: grid legality, theme entry "
            "placement, fill quality gates, clue conventions, and house voice. Use when "
            "working on puzzle generation, validation, or QA."
        ),
        stages=(Stage.THEME_IDEATION, Stage.CLUE_WRITING, Stage.EDITORIAL_QA),
    ),
    SkillSpec(
        name="braingames-user-input",
        description=(
            "How to handle player-authored input for crossword themes: normalizing free "
            "text to the taxonomy, resolving ambiguity, sparse and conflicting profiles, "
            "sensitive topics, and prompt-injection defence. Use when touching profile "
            "ingestion or anything that puts player text into a prompt."
        ),
        stages=(Stage.PROFILE_CLASSIFICATION,),
    ),
)


def documents_for(kb: KnowledgeBase, spec: SkillSpec) -> list[Doc]:
    seen: dict[str, Doc] = {}
    for stage in spec.stages:
        for doc in kb.active(stage):
            seen[doc.ref] = doc
    return sorted(seen.values(), key=sort_key)


def render_skill(spec: SkillSpec, docs: list[Doc], kb_version: str) -> str:
    """Build one SKILL.md.

    Bodies are inlined rather than referenced. A skill that points at files the
    agent must then go and open loses to one that just contains the content, and
    these sets are small enough that the token cost is worth the reliability.
    """
    lines = [
        "---",
        f"name: {spec.name}",
        f"description: {spec.description}",
        "---",
        "",
        GENERATED_MARKER,
        f"<!-- kb_version: {kb_version} -->",
        "",
        f"# {spec.name}",
        "",
        "The content below is the project's knowledge base, published for coding agents.",
        "It is generated from `knowledge/` — to change any of it, edit the source document",
        "and run `bg kb sync-skills`.",
        "",
    ]

    if not docs:
        lines += [
            "_No documents are published for this skill yet._",
            "",
            "Add one with `bg kb new`, tagging it with the relevant `applies_to` stage.",
            "",
        ]
        return "\n".join(lines)

    lines.append("## Contents")
    lines.append("")
    for doc in docs:
        lines.append(f"- **{doc.ref}** — {doc.meta.summary.strip()}")
    lines.append("")

    for doc in docs:
        lines += ["---", "", f"## {doc.ref}", "", doc.body.strip(), ""]

    return "\n".join(lines)


@dataclass
class SyncResult:
    written: list[Path]
    removed: list[Path]
    empty: list[str]

    @property
    def changed(self) -> bool:
        return bool(self.written or self.removed)


def sync(
    kb: KnowledgeBase,
    skills_root: Path,
    *,
    prune: bool = True,
    dry_run: bool = False,
) -> SyncResult:
    """Regenerate ``.claude/skills/`` from the knowledge base."""
    written: list[Path] = []
    empty: list[str] = []
    kb_version = kb.version()
    expected: set[str] = set()

    for spec in SKILLS:
        docs = documents_for(kb, spec)
        if not docs:
            empty.append(spec.name)
        expected.add(spec.name)

        target = skills_root / spec.name / "SKILL.md"
        content = render_skill(spec, docs, kb_version)

        if target.exists() and target.read_text(encoding="utf-8") == content:
            continue
        if not dry_run:
            atomic_write(target, content)
        written.append(target)

    removed: list[Path] = []
    if prune and skills_root.is_dir():
        for child in sorted(skills_root.iterdir()):
            if not child.is_dir() or child.name in expected:
                continue
            # Only reclaim directories this command generated. A hand-written
            # skill living alongside is not ours to delete.
            skill_file = child / "SKILL.md"
            if skill_file.exists() and GENERATED_MARKER in skill_file.read_text(encoding="utf-8"):
                removed.append(child)
                if not dry_run:
                    shutil.rmtree(child)

    return SyncResult(written=written, removed=removed, empty=empty)


def check(kb: KnowledgeBase, skills_root: Path) -> list[str]:
    """Return skills whose published content is out of date.

    Wired into CI so a knowledge change that forgets the sync fails the build
    rather than leaving coding agents on stale guidance.
    """
    stale: list[str] = []
    kb_version = kb.version()
    for spec in SKILLS:
        target = skills_root / spec.name / "SKILL.md"
        expected = render_skill(spec, documents_for(kb, spec), kb_version)
        if not target.exists() or target.read_text(encoding="utf-8") != expected:
            stale.append(spec.name)
    return stale


__all__ = ["SKILLS", "SkillSpec", "SyncResult", "check", "documents_for", "render_skill", "sync"]
